project:
  type: website
  output-dir: docs

website:
  title: "Juan Camilo Rodriguez — MBA Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects
      - href: skills.qmd
        text: Skills
      - href: leadership.qmd
        text: Leadership
  page-footer:
    left: "<span id='y'></span> Juan Camilo Rodriguez"
    right: "Built with Quarto"

format:
  html:
    theme:
      - superhero
    toc: false
    page-layout: full
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    include-after-body:
      text: |
        <script>
          // writes: © 2025 (current year)
          const y = document.getElementById('y');
          if (y) y.textContent = '© ' + new Date().getFullYear();
        </script>