project:
  type: website
  output-dir: docs

website:
  title: "Juan Camilo Rodriguez — MBA Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects
      - href: skills.qmd
        text: Skills
      - href: leadership.qmd
        text: Leadership
  page-footer:
    left: "© {{< meta year >}} Juan Camilo Rodriguez"
    right: "Built with Quarto"

format:
  html:
    theme:
      - superhero
    toc: false
    page-layout: full
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    css: styles.css